[features]
seeds = false
skip-lint = false

[programs.localnet]
taxpay = "2kBACGEWnZHaiLPySUCudChBKRc57L49PVaCotGZrbyk"

[programs.devnet]
taxpay = "2kBACGEWnZHaiLPySUCudChBKRc57L49PVaCotGZrbyk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.31.0"